In [3]:
import pandas as pd

In [34]:
df = pd.read_csv("dirty_dataset.csv")

In [5]:
df.head()

,id,name,age,gender,salary,joining_date,department,email
0,1,John Doe,28,Male,50000,2021-05-10,Engineering,john.doe@email.com
1,2,Jane Smith,NaN,Female,60000,10/06/2020,HR,janesmith@email.com
2,3,Bob Johnson,thirty,Male,55000,2019-07-15,Engineering,bob.j@email
3,4,Alice Brown,25,Female,NaN,2022-01-20,Marketing,alice.brown@email.com
4,5,Chris Green,40,Male,70000,2020/03/12,Finance,chris.green@email.com

In [6]:
df.tail()

,id,name,age,gender,salary,joining_date,department,email
10,11,Olivia Martin,26,Female,57000,NaN,HR,olivia.martin@email.com
11,12,Noah Clark,33,Male,72000,2019-09-10,Engineering,noah.clark@email.com
12,13,Sophia Lewis,abc,Female,61000,2021-04-18,Marketing,sophia.lewis@email.com
13,14,James Walker,45,Male,80000,2017-06-25,Finance,james.walker@email.com
14,15,Isabella Hall,29,Female,59000,2021-07-11,HR,isabella.hall@email

In [8]:
df.describe()

              id
count  15.000000
mean    8.000000
std     4.472136
min     1.000000
25%     4.500000
50%     8.000000
75%    11.500000
max    15.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 0 to 14
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            11 non-null     int64
 1   name          11 non-null     object
 2   age           11 non-null     object
 3   gender        11 non-null     object
 4   salary        11 non-null     object
 5   joining_date  11 non-null     object
 6   department    11 non-null     object
 7   email         11 non-null     object
dtypes: int64(1), object(7)
memory usage: 792.0+ bytes

In [15]:
df.duplicated().sum()

0

In [20]:
df.isnull().sum()

id              0
name            0
age             0
gender          0
salary          0
joining_date    0
department      0
email           0
dtype: int64

In [35]:
df = df.dropna()

In [42]:
df.head()

,id,name,age,gender,salary,joining_date,department,email
0,1,John Doe,28,Male,50000,2021-05-10,Engineering,john.doe@email.com
2,3,Bob Johnson,thirty,Male,55000,2019-07-15,Engineering,bob.j@email
4,5,Chris Green,40,Male,70000,2020/03/12,Finance,chris.green@email.com
5,6,John Doe,28,Male,50000,2021-05-10,Engineering,john.doe@email.com
7,8,David Lee,29,Male,not_available,2021-08-25,Engineering,david.lee@email.com